type: module
name: 'Config Delete'
description: 'Delete configuration items from the UI.'
package: 'Development'
core_version_requirement: ^10 || ^11
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2024-12-21
version: '2.0.3'
project: 'config_delete'
datestamp: 1734796617
